// File: middleware.go
//
// Responsibility:
//   - Apply lightweight HTTP security policies to Web responses.
//   - Add defensive HTTP headers.
//   - Record minimal technical request information for diagnostics.
//
// Receives:
//   - HTTP requests.
//   - Next HTTP handler.
//
// Produces:
//   - HTTP responses with defensive headers.
//   - Minimal diagnostic logs written to stdout.
//
// Previous logical stage:
//   - server.go.
//
// Next logical stage:
//   - Registered Web routes and handlers.
//
// Important restrictions:
//   - Must not perform conversions.
//   - Must not inspect units.
//   - Must not contain scientific logic.
//   - Must not alter request bodies.
//   - Must not log request bodies or user conversion expressions.
//   - Must not log cookies or complete HTTP headers.
//   - IP information is diagnostic only and must not currently
//     be used for blocking or rate limiting.
package web

import (
	"log"
	"net"
	"net/http"
	"time"
)

// responseRecorder captures the HTTP status code returned by
// downstream handlers.
//
// Receives:
//   - Original http.ResponseWriter.
//
// Produces:
//   - Normal HTTP response while retaining its status code.
//
// Previous logical stage:
//   - loggingMiddleware.
//
// Next logical stage:
//   - Original ResponseWriter.
//
// Important restrictions:
//   - Must not inspect or modify response content.
//   - Must preserve normal ResponseWriter behavior.
type responseRecorder struct {
	http.ResponseWriter
	statusCode int
}

// WriteHeader records and forwards the HTTP status code.
func (r *responseRecorder) WriteHeader(statusCode int) {
	r.statusCode = statusCode
	r.ResponseWriter.WriteHeader(statusCode)
}

// Write records an implicit 200 OK when the handler writes a body
// without previously calling WriteHeader.
func (r *responseRecorder) Write(data []byte) (int, error) {
	if r.statusCode == 0 {
		r.statusCode = http.StatusOK
	}

	return r.ResponseWriter.Write(data)
}

// securityHeadersMiddleware adds basic defensive HTTP headers
// to every response produced by the Web application.
//
// Receives:
//   - Next HTTP handler.
//
// Produces:
//   - Wrapped HTTP handler.
//
// Important restrictions:
//   - Must remain lightweight.
//   - Must not block legitimate requests.
//   - Must not contain route-specific logic.
func securityHeadersMiddleware(
	next http.Handler,
) http.Handler {
	return http.HandlerFunc(
		func(
			w http.ResponseWriter,
			r *http.Request,
		) {
			w.Header().Set(
				"X-Content-Type-Options",
				"nosniff",
			)

			w.Header().Set(
				"Referrer-Policy",
				"strict-origin-when-cross-origin",
			)

			next.ServeHTTP(w, r)
		},
	)
}

// loggingMiddleware records minimal technical information about
// each HTTP request.
//
// Receives:
//   - HTTP request.
//   - Response generated by downstream handlers.
//
// Produces:
//   - Normal HTTP response.
//   - One compact diagnostic log entry.
//
// Important restrictions:
//   - Must not log request bodies.
//   - Must not log conversion expressions.
//   - Must not log cookies.
//   - Must not dump complete request headers.
//   - X-Forwarded-For is recorded only for diagnostics.
//   - Proxy-provided IP information must not yet be trusted for
//     security decisions.
func loggingMiddleware(
	next http.Handler,
) http.Handler {
	return http.HandlerFunc(
		func(
			w http.ResponseWriter,
			r *http.Request,
		) {
			start := time.Now()

			recorder := &responseRecorder{
				ResponseWriter: w,
			}

			next.ServeHTTP(recorder, r)

			statusCode := recorder.statusCode
			if statusCode == 0 {
				statusCode = http.StatusOK
			}

			remoteIP := r.RemoteAddr

			if host, _, err := net.SplitHostPort(
				r.RemoteAddr,
			); err == nil {
				remoteIP = host
			}

			forwardedFor := r.Header.Get(
				"X-Forwarded-For",
			)
			if forwardedFor == "" {
				forwardedFor = "-"
			}

			cfRay := r.Header.Get("CF-Ray")
			if cfRay == "" {
				cfRay = "-"
			}

			log.Printf(
				"HTTP method=%s path=%s status=%d duration=%s remote_ip=%s forwarded_for=%s cf_ray=%s",
				r.Method,
				r.URL.Path,
				statusCode,
				time.Since(start),
				remoteIP,
				forwardedFor,
				cfRay,
			)
		},
	)
}
